"""init

Revision ID: 1afd45e038d1
Revises: 
Create Date: 2019-06-09 08:59:14.407407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1afd45e038d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dept',
    sa.Column('deptno', mysql.INTEGER(display_width=2), nullable=False),
    sa.Column('dname', sa.String(length=14), nullable=True),
    sa.Column('loc', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('deptno')
    )
    op.create_table('salgrade',
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('losal', sa.Integer(), nullable=True),
    sa.Column('hisal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('grade')
    )
    op.create_table('stu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('hometown', sa.String(length=30), nullable=True),
    sa.Column('fscore', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emp',
    sa.Column('empno', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('ename', sa.String(length=10), nullable=True),
    sa.Column('job', sa.String(length=10), nullable=True),
    sa.Column('mgr', mysql.INTEGER(display_width=4), nullable=True),
    sa.Column('hiredate', sa.DATE(), nullable=True),
    sa.Column('sal', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('comm', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('deptno', mysql.INTEGER(display_width=2), nullable=False),
    sa.ForeignKeyConstraint(['deptno'], ['dept.deptno'], ),
    sa.PrimaryKeyConstraint('empno')
    )
    op.create_table('scores',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stuid', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('subid', sa.Integer(), nullable=True),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['stuid'], ['stu.id'], ),
    sa.ForeignKeyConstraint(['subid'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('emp')
    op.drop_table('subjects')
    op.drop_table('stu')
    op.drop_table('salgrade')
    op.drop_table('dept')
    op.drop_table('areas')
    # ### end Alembic commands ###
