"""auto_increment

Revision ID: 547dc0ba55f3
Revises: 91ebe7fcd78a
Create Date: 2020-08-30 11:58:42.745531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547dc0ba55f3'
down_revision = '91ebe7fcd78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
