"""work

Revision ID: 91ebe7fcd78a
Revises: 1afd45e038d1
Create Date: 2020-08-29 10:03:32.452121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91ebe7fcd78a'
down_revision = '1afd45e038d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('res_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('routing_key', table_name='message_template')
    op.drop_table('message_template')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('target', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('verification_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True),
    sa.Column('routing_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), server_default=sa.text("''"), nullable=True),
    sa.Column('template_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), server_default=sa.text("''"), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('message_template',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('routing_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('routing_key', 'message_template', ['routing_key'], unique=True)
    op.drop_table('resource')
    op.drop_table('region')
    op.drop_table('phone')
    op.drop_table('address')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
